version: "3.9"

services:
  db:
    image: postgres:14.6-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
